server:
    port: 8088
    servlet:
       context-path: /robot
    tomcat:
       uri-encoding: UTF-8
spring:
    profiles:
        active: dev
    servlet:
       multipart:
          max-request-size: 2MB
          max-file-size: 2MB            
    mvc:
       static-path-pattern: /static/**
    http:
       encoding:
         charset: UTF-8
         enabled: true
         force: true
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.hs.mapper
    config-location: classpath:mybatis-config.xml
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
swagger:
   enable: true