package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.3
 * 2019-08-26T20:36:20.434+08:00
 * Generated source version: 3.3.3
 *
 */
@WebServiceClient(name = "VasWebService",
                  wsdlLocation = "http://172.23.35.203:8733/VasWebService/?singlewsdl",
                  targetNamespace = "http://tempuri.org/")
public class VasWebService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://tempuri.org/", "VasWebService");
    public final static QName BasicHttpBindingIVasWebService = new QName("http://tempuri.org/", "BasicHttpBinding_IVasWebService");
    static {
        URL url = null;
        try {
            url = new URL("http://172.23.35.203:8733/VasWebService/?singlewsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VasWebService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://172.23.35.203:8733/VasWebService/?singlewsdl");
        }
        WSDL_LOCATION = url;
    }

    public VasWebService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VasWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VasWebService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VasWebService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VasWebService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VasWebService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns IVasWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IVasWebService")
    public IVasWebService getBasicHttpBindingIVasWebService() {
        return super.getPort(BasicHttpBindingIVasWebService, IVasWebService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IVasWebService
     */
    @WebEndpoint(name = "BasicHttpBinding_IVasWebService")
    public IVasWebService getBasicHttpBindingIVasWebService(WebServiceFeature... features) {
        return super.getPort(BasicHttpBindingIVasWebService, IVasWebService.class, features);
    }

}
